name: Web Scraping CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with your requirements file name

    - name: Print from test.py
      run: |
          export INPUT_STORE=$(python optimizedScraper.py)
          echo "Script Status: "
          echo $INPUT_STORE

    - name: Run scraping script
      run: python newSnak.py  # Replace with your Python script name

    - name: Upload XML result
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: ./new_strain_data.xlsx  # This will upload the XML result to the repository root

    # Add additional steps if needed, e.g., storing the results, deploying, etc.
