name: Web Scraping CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraping script
      run: python gptTest.py

    # - name: Upload results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: results
    #     path: ./

    # Add additional steps if needed, e.g., storing the results, deploying, etc.
